# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"lambda_handler": "app.ipynb"}

modules = ["app.py"]

doc_url = "https://fastai.github.io/helloWorld/"

git_url = "https://github.com/fastai/helloWorld/tree/master/"

def custom_doc_links(name): return None
