# AUTOGENERATED! DO NOT EDIT! File to edit: app.ipynb (unless otherwise specified).

__all__ = ['lambda_handler']

# Cell
from awsSchema.apigateway import Event, Response
import json

# Cell
def lambda_handler(event,*args):
  body = Event.parseBody(event)
  return Response.returnSuccess(body={'message':'helloWorld'})